### ISSUE TITLE
jquery conflict problem

### ISSUE THREAD

**Issue by blue-farid** [omidp/pfaces#1]
hey! =)
I was looking for a jsf jalali calendar, so I found yours.
I tested project in a empty web app project, It works fine.
but I want add this in a real project (a spring boot web application) that uses primefaces components too.
It should not be a problem, but the page does not load at all!
there is no exeption, but I see some errors in browser console. here is the error:

Uncaught TypeError: this.jq.layout is not a function
    at c._render (layout.js.do?ln=primefaces&v=8.0:2)
    at c.renderDeferred (core.js.do?ln=primefaces&v=8.0:22)
    at c.init (layout.js.do?ln=primefaces&v=8.0:2)
    at c.e.<computed> [as init] (core.js.do?ln=primefaces&v=8.0:22)
    at new c (core.js.do?ln=primefaces&v=8.0:22)
    at Object.createWidget (core.js.do?ln=primefaces&v=8.0:16)
    at Object.cw (core.js.do?ln=primefaces&v=8.0:16)
    at HTMLDocument.<anonymous> (passwordOperation.do:775)
    at o (pfaces.js.do?ln=pfaces:2)
    at Object.fireWith (pfaces.js.do?ln=pfaces:2)

could you please help me if have an Idea? I searched for a long time but I did not find the solution.
thanks!

**Comment by omidp** [comment]
Hi,

Which version of Primefaces you are using ? it should work with primefaces **6.1** . 
Latest version of Primefaces is using different jQuery library as a result I think there are conflicts . 

Please check [this project ](https://github.com/omidp/bootfaces) for Spring boot and Primefaces configuration if you want deploy your project as war .

Please check [this project](https://github.com/omidp/bootfacesjar)   for Spring boot and Primefaces configuration if you want deploy your project as jar .

And check [this project](https://github.com/omidp/primefaces/commit/07de1c599346e23ab62e4bfe8ab26703b823fe32) to use custom primefaces for datepicker.

**Comment by blue-farid** [comment]
yes It is the latest version, I am using primefaces 8.0
thank you for your help. I will try this!
